### PR TITLE
Add base token store to ecosystem

### PR DESCRIPTION
**Pull request by mykcryptodev**
**What changed? Why?**
- Added Base Token Store to the ecosystem list so that people can find the store if they are interested in buying tokens on Base in an easy and familiar UX of an e-commerce site.

**Notes to reviewers**
- I did not see a pattern (like alphabetical order) for adding to the ecosystem json so I added my entry to the bottom

**How has it been tested?**
- I tested it visually on my local env by scrolling to find it, searching it by name, using the defi pill to find it in the filtered category, and clicking through it to the proper url

### CODE REVIEW

**Comment by wbnns** [comment]
@mykcryptodev 

Heya Myk, thanks so much for submitting this and also until we had a chance to review! It looks awesome. We aren't adding direct token sales and listings to the Ecosystem page at this time (it's not just specific to your project, there aren't any others in the directory, either) but I would definitely consider submitting a request to add this to the [registry](https://base.org/registry) though if you haven't already!

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by mykcryptodev** [comment]
Understood - ty for letting me know - Registry form is submitted :)

**Comment by mykcryptodev** [comment]
@wbnns has there been a change in what would be acceptable to submit? Would this PR be reconsidered?

**Pull request closed without merging**
