### PR TITLE
Added openseason project to ecosystem.json

### PR DESCRIPTION
**Pull request by bowsernet**
**What changed? Why?**

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by wbnns** [comment]
@bowsernet 

Thanks for this PR! This looks super interesting. Can you please clarify how people play this on Base and what portions of the game are onchain?

**Comment by bowsernet** [comment]
@wbnns Thank you!
Game access, player rewards, and our referral program are all onchain. Players make a one-time connection between their Epic Games account and their wallet (including Coinbase Smart Wallet) which makes them eligible to earn onchain rewards and enables NFT enhanced gameplay.

Staking is also onchain - anyone can stake on players and earn rewards, similar to mainstream eSports staking programs but all onchain.

We have bridged our studio token to Base and are working to make all of the above mentioned onchain programs available on Base as well. Our team is in touch with Sam Frankel and team.

**Comment by wbnns** [comment]
@bowsernet 

Hi there! Thanks for your patience. Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please drop the tag and define the category and subcategory to `consumer` and `gaming`?

We'll do our best to complete the review as soon as possible once you do! 🙏

**Comment by wbnns** [comment]
@bowsernet 

Please also rebase and sign your commit.

**Comment by wbnns** [comment]
@bowsernet Please open a new PR once changes have been made. 🙏

**Pull request closed without merging**
