### PR TITLE
Rename Base Camp to Base Learn

### PR DESCRIPTION
**Pull request by briandoyle81CB**
**What changed? Why?**
Change text from Base Camp to Base Learn

**Notes to reviewers**
Does NOT change the graphics!

**How has it been tested?**

### CODE REVIEW

**Comment by zencephalon** [comment]
@briandoyle81CB looks like this got a merge conflict

**Comment by briandoyle81CB** [comment]
> @briandoyle81CB looks like this got a merge conflict

@zencephalon fixed but I accidentally pulled some prior commits from others.  That won't matter when it gets squashed, right?

**Comment by zencephalon** [comment]
@briandoyle81CB should be fine

**Review by hughescoin — APPROVED** [review]
LGTM tested locally

**Pull request merged**
