### PR TITLE
Add OG data for builder summer

### PR DESCRIPTION
**Pull request by zencephalon**
**What changed? Why?**

Adds OG image and description for the Onchain Summer builder page.

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Review by niran — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for niran @ 2024-05-17 16:47:02 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by niran-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for niran-cb @ 2024-05-17 16:48:07 UTC
User must have write permissions to review

**Comment by cb-heimdall** [comment]
Review Error for niran @ 2024-05-17 17:04:20 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by dneilroth — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for dneilroth @ 2024-05-17 17:20:22 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by aflock — APPROVED** [review]

**Pull request merged**
