### PR TITLE
Added Moralis to node provider list

### PR DESCRIPTION
**Pull request by filipmartinsson**
**What changed? Why?**
Moralis added RPC for base

**Notes to reviewers**

**How has it been tested?**

**Does this PR add a new token to the bridge?**

Are you adding an entry to [`assets.ts`](../apps/bridge/assets.ts)?

- [ ] No, this PR does not add a new token to the bridge
- [ ] Yes, and I've confirmed this token doesn't use a bridge override
- [ ] Yes, and I've confirmed this token is an OptimismMintableERC20

If you are adding a token to the bridge, please include evidence of both confirmations above for your reviewers.

### CODE REVIEW

**Review by taycaldwell — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for taycaldwell @ 2024-04-24 20:30:05 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by wbnns — CHANGES_REQUESTED** [review]
@filipmartinsson 

Heya, thanks for the PR! Could you please revise to:

>[Moralis](https://moralis.io/chains/base/?utm_source=base-docs&utm_medium=partner-docs) is a leading provider of APIs and RPCs for Base as well as other major EVM networks. Moralis is SOC2 Type 2 certified.

Note: I also updated the link to go to the Base-specific landing page rather than the homepage.

**Comment by wbnns** [comment]
@filipmartinsson Hello, since it's been a while and we haven't heard back, closing this PR for now. If you'd still like to pursue, please let us know and we can reopen.

**Comment by bharathbabu68** [comment]
Hey @wbnns , hope you're well, could you please reopen the PR so that we can make the changes as mentioned

**Pull request closed without merging**
