### PR TITLE
Add Talentir

### PR DESCRIPTION
**Pull request by johanneskares**
**What changed? Why?**

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — APPROVED** [review]
ACK

@johanneskares Thanks for building on Base 🔵

**Comment by johanneskares** [comment]
> ACK
> 
> @johanneskares Thanks for building on Base 🔵

Great, anything I can do go the this merged? The merge seems blocked.

**Review by wbnns — APPROVED** [review]

**Comment by johanneskares** [comment]
@wbnns 

seems like the builds are not reporting, that's why merge is blocked

**Comment by wbnns** [comment]
@johanneskares Thanks for reporting; I'm flagging this internally and we'll take a look as soon as possible. It may take some extra time due to some of the team having limited availability for non-urgent issues in the midst of the holidays. We appreciate the patience. 🙏

**Review by wbnns — APPROVED** [review]

**Comment by wbnns** [comment]
@johanneskares Nevermind, fixed now :)

**Comment by johanneskares** [comment]
amazing thanks

**Pull request merged**
