### PR TITLE
Add Metacade to Ecosystem page

### PR DESCRIPTION
**Pull request by soheimam**
**What changed? Why?**
Adding Metacade to the ecosystem section

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@soheimam 

Thanks for this PR! Could you please update the linked page to point to where it is possible for Base users to land so they can play games, in order for us to review?

**Comment by soheimam** [comment]
great thanks @wilsoncusack  have updated

**Comment by wbnns** [comment]
Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please update the category and subcategory?

We'll do our best to review as soon as possible once you do! 🙏

**Comment by wbnns** [comment]
@soheimam 

Please also rebase to resolve the merge conflict.

**Comment by wbnns** [comment]
Please open a new PR, when you are ready, incorporating the above changes. 🙏

**Pull request closed without merging**
