### PR TITLE
Docs updated for The Graph: Supports both mainnet & testnet. +Cleanup

### PR DESCRIPTION
**Pull request by alinobrasil**
**What changed? Why?**
 - Supported networks - Only showed mainnet. The Graph supports both Mainnet & Testnet
 - Overall wording - Simplified to highlight benefits/features in bullet points.

**Notes to reviewers**
We wanted to make sure devs know they can build subgraphs on Testnet too, to make their transition to mainnet as seameless as possible.
The docs were also updated to be clear & concise with The Graph's benefits & features. 

**How has it been tested?**
Looks fine locally.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — APPROVED** [review]
ACK

@alinobrasil Thanks for building on Base 🔵

**Comment by cb-heimdall** [comment]
Review Error for wbnns @ 2024-12-06 17:26:27 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by wbnns — APPROVED** [review]

**Review by hughescoin — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for hughescoin @ 2024-12-09 22:45:32 UTC
User cannot review their own commit

**Review by ericbrown99 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for ericbrown99 @ 2024-12-10 01:50:01 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by wbnns — APPROVED** [review]
@alinobrasil Thanks!

**Pull request merged**
