### PR TITLE
Add DOB Base Multisender

### PR DESCRIPTION
**Pull request by DOBonBase**
**What changed? Why?**
Add DOB Base Multisender Tool
**Notes to reviewers**
Tested, only on Base and work well
**How has it been tested?**
Our Developers and some users, work fine in Base without any issue. Multisender contract is verified

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@DOBonBase

Hi there! Thanks for building on Base! Can you please change the `tag` to `infra`?

**Comment by DOBonBase** [comment]
> @DOBonBase is attempting to deploy a commit to the **Coinbase** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=Coinbase&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%2208641e10731dfa37885c34b69a52889195da2d93%22%7D%2C%22id%22%3A%22QmaKKeusrg6K8GzwRU4VodxwTGKiZ9Wkq4pBoghqJDkSe8%22%2C%22org%22%3A%22base-org%22%2C%22prId%22%3A1256%2C%22repo%22%3A%22web%22%7D).

Done

**Comment by wbnns** [comment]
@DOBonBase 

Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please rebase + update your PR, conforming to the new format by removing the tag, and defining the category (consumer) and subcategory (gaming)?

We'll do our best to review as soon as possible once you do! 🙏

**Comment by DOBonBase** [comment]
> @DOBonBase
> 
> Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please rebase + update your PR, conforming to the new format by removing the tag, and defining the category (consumer) and subcategory (gaming)?
> 
> We'll do our best to review as soon as possible once you do! 🙏

Ok

**Pull request closed without merging**
