### PR TITLE
basedart and basedselfies web ecosystem

### PR DESCRIPTION
**Pull request by barigyasi**
**What changed? Why?**
added BASEDART and BASEDSELFIES to the ecosystem page
**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by wbnns** [comment]
@barigyasi 

Thanks for the updated PR. In review there are some issues:

* For BASEDART it seems there are currently only two art pieces in the marketplace; could you confirm if this is correct?
+ For BASEDSELFIES the upload feature does not seem to be working; please fix

Also, please rebase and fix the merge conflict. 🙏

**Comment by barigyasi** [comment]
Yes there is only 1 nft minted on the collection so far I’m in the process
of scanning new artwork from artist currently and trying to raise funds for
a better scanner and computer to process the artwork.

That is weird for the upload error, did you name the nft? Can you share the
console with me please?

Tabari Humphries ;
Founder @ MetaPhysical Art Institute - www.metaphysicalart.io

**Comment by wbnns** [comment]
@barigyasi Thanks for the info. Since the rebase still needs to be done, can you please split this into two separate PRs, one for each site?

**Pull request closed without merging**
