### PR TITLE
CryptoChill

### PR DESCRIPTION
**Pull request by alittleframe**
Hi,

I've added our project CryptoChill to the ecosystem.json file and added a PNG of our logo to the public/images/partners folder.

Thanks,
Matthew

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@alittleframe 

Thanks for this PR! Could you all please update the landing page to something specifically focused for Base users that would be coming from base.org, and change the tag from `wallet` to `infra`?

**Comment by cb-heimdall** [comment]
Review Error for wbnns @ 2024-12-05 17:04:08 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by wbnns** [comment]
Closing due to inactivity

**Pull request closed without merging**
