### PR TITLE
Re-Submission ArtGridz

### PR DESCRIPTION
**Pull request by Dabus123**
Re-submission Notice: The correct domain for our platform is artgridz.decentraplace.io. The previous submission mistakenly used a .com ending.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by wbnns** [comment]
@Dabus123 

Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please rebase + update your PR, conforming to the new format by removing the tag, and defining the category (consumer) and subcategory (nft)?

We'll do our best to review as soon as possible once you do! 🙏

**Comment by Dabus123** [comment]
Hi @wbnns,

Happy to hear from you! Thanks for letting me know!—I’ll go ahead and
remove the tag and define the category to 'consumer' and subcategory to
'nft'. Will call this fork 'artgridz' & Owner = Dabus123

Best regards, dabus.eth

Am Do., 19. Dez. 2024 um 22:25 Uhr schrieb wbnns ***@***.***>:

**Comment by Dabus123** [comment]
I opened the new PR but I keep getting the following error message when I try to open it:

'
**This repository is temporarily unavailable.**
The backend storage is temporarily offline. Usually this means the storage server is undergoing maintenance.
'

**Pull request closed without merging**
