### PR TITLE
Add SEDA to Ecosystem page

### PR DESCRIPTION
**Pull request by mariocao**
**What changed? Why?**
`ecosystem.json` was updated to include SEDA and a logo was added to `public/images/partners`.

**Notes to reviewers**
Thanks! :)

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@mariocao 

Thanks for this PR! Please update the landing page URL to a Base-specific landing page that people coming from base.org can seamlessly get started on, and resubmit so that we can review. 🙏

**Comment by mariocao** [comment]
> @mariocao
> 
> Thanks for this PR! Please update the landing page URL to a Base-specific landing page that people coming from base.org can seamlessly get started on, and resubmit so that we can review. 🙏

Hi, thank you for reviewing the PR!

As an infrastructure protocol aiming to support hundreds of chains, we usually don’t spin up dedicated landing pages.

We tried to follow the guidelines in the README and referenced similar projects (which also seem to link to their main landing page). Did we miss something in the guidelines? Appreciate your feedback, and we’re happy to help however we can.

**Comment by wbnns** [comment]
@mariocao 

Thanks for the reply! Since users from base.org would be coming to SEDA to use it, it would be helpful if you all have a landing page with information on how to get started. Currently it is unclear; do you have a page in the docs about how builders can use SEDA on Base that you could update the link to point to instead?

**Comment by wbnns** [comment]
@mariocao Please open a new PR when you can make this change and we'll re-review. 👍

**Pull request closed without merging**
