### PR TITLE
Add Registry API docs to left side nav

### PR DESCRIPTION
**Pull request by neodaoist**

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@neodaoist 

Heya, apologies, it's not documented very well; this change should go in `apps/base-docs/sidebars.js` instead of `base-docs/src/pages/index.tsx` (it won't appear to the end user if in `index.tsx`).

**Comment by cb-heimdall** [comment]
Review Error for wbnns @ 2024-07-22 11:13:32 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by wbnns — COMMENTED** [review]
Resubmitting to Heimdall

**Review by wbnns — APPROVED** [review]
ACK

**Review by brendan-defi — APPROVED** [review]

**Pull request merged**
