### PR TITLE
chore: remove @next/font from bridge workspace

### PR DESCRIPTION
**Pull request by JFrankfurt**
**What changed? Why?**
- `@next/font` https://www.npmjs.com/package/@next/font should no longer be used. It's included with `next` as of 13.2.0
- our version in package.json allowed 13.1.x, but our yarn.lock was already resolving to 13.5.x. This caused us to get a warning in the console about removing the unneeded dep.

NO VISUAL CHANGE:
|before|after|
|-|-|
|image|image

**Notes to reviewers**

**How has it been tested?**
visual comparison btwn local and prod indicates no font change

### CODE REVIEW

**Review by brendan-defi — APPROVED** [review]
tested locally and confirm no font changes.

lgtm

**Comment by cb-heimdall** [comment]
Review Error for brendan-defi @ 2024-06-13 17:49:56 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by brendan-defi — APPROVED** [review]
tested locally and confirm no font changes. 

lgtm

**Review by wbnns — APPROVED** [review]
utACK

**Pull request merged**
