### PR TITLE
chore: add Swedish & Thai translations of "Base is for everyone" on homepage

### PR DESCRIPTION
**Pull request by asianviking**
**What changed? Why?**
Add Swedish & Thai translations of "Base is for everyone" on homepage

**Notes to reviewers**

**How has it been tested?**
- Run `yarn workspace @app/web dev`
- Navigate to `http://localhost:3000` in your browser
- Make sure the slider is working as expected

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by cb-heimdall** [comment]
Review Error for derRizzMeister @ 2024-11-23 14:33:44 UTC
User must have write permissions to review

**Comment by wbnns** [comment]
@asianviking 

Hi there! Thanks for contributing to Base! Could you please resolve the merge conflict?

**Comment by asianviking** [comment]
Heya @wbnns ! Conflicts should be resolved now. Ty!

**Review by wbnns — APPROVED** [review]
@asianviking Ty!

**Pull request merged**
