### PR TITLE
Add Minimatch to Ecosystem

### PR DESCRIPTION
**Pull request by VISHWAJ33T**
**What changed? Why?**

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@VISHWAJ33T 

Thanks for this PR! In review:
1. It appears a ";" briefly appears when trying to load this page
2. Can you please update 'on-chain' to be spelled 'onchain'

**Comment by VISHWAJ33T** [comment]
@wbnns

Thanks for the review!

1.Removed the `;` that was appearing on page load.
2.Updated all instances of "on-chain" to "OnChain".

Let me know if there’s anything else!

**Comment by wbnns** [comment]
@VISHWAJ33T 

Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please update the category + subcategory?

We'll do our best to review as soon as possible once you do! 🙏

**Comment by VISHWAJ33T** [comment]
@wbnns 

Hi there! Thanks for letting me know. I have updated the file and added the category and subcategory as requested. Looking forward to your review! 😊

**Review by wbnns — APPROVED** [review]
ACK

@VISHWAJ33T Thanks for building on Base! 🔵

**Pull request merged**
