### PR TITLE
Add ECOIN Wallet to Base Ecossystem

### PR DESCRIPTION
**Pull request by ecoin-finance**
**What changed? Why?**
- Initial submission of the ECOIN Wallet app to the Base ecosystem.

**Notes to reviewers**
- The ECOIN Wallet is a cryptocurrency wallet available exclusively for Android devices.
- The app is public and receives regular updates to enhance functionality.
- The latest update includes full support for Base, with features like Deposit, Withdraw, Swap, and Cross-Chain functionality powered by ZetaChain.

**How has it been tested?**
- The app is live and available on Google Play for testing: [ECOIN Wallet on Google Play](https://play.google.com/store/apps/details?id=org.ecoinwallet)  

**To test:**  
1. Create or connect a wallet within the app.  
2. Select **Multichain**, or for the best results, choose **Base** as the network.  
3. Test the following supported features:  
   - Deposit and Withdraw on Base.  
   - Swap functionality built directly into the wallet.  
   - Cross-chain swaps powered by ZetaChain.  
   - Seamless DApp integration.  

### Screenshots  

Below are screenshots of the **ECOIN Wallet** app showcasing its features with Base integration:  

| base (1) | base (2) | base (3) |
|:-------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------:|

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by ecoin-finance** [comment]
@cb-heimdall Could you please review it for me?

**Comment by ecoin-finance** [comment]
@cb-heimdall Could you please review it for me?

**Comment by ecoin-finance** [comment]
@cb-heimdall Could you please review it for me?

**Comment by ecoin-finance** [comment]
@cb-heimdall Could you please review it for me?

**Comment by ecoin-finance** [comment]
Why is so hard to do this?

**Comment by wbnns** [comment]
@ecoin-finance 

Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please rebase + update your PR, conforming to the new format by removing the tag, and defining the category and subcategory?

We'll do our best to review as soon as possible once you do! 🙏

**Pull request closed without merging**
