### PR TITLE
Maintaining Consistent Numbering for Improved Readability

### PR DESCRIPTION
**Pull request by sky-coderay**
**What changed? Why?**
##Incorrect numbering can confuse the reader, especially in lengthy or complex documents. Consistent numbering makes it easier to locate the desired sections quickly.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by sky-coderay** [comment]
@brendan-defi I reviewed all MD files and fixed critical numbering issues to prevent reader confusion. The docs will soon be flawless, and everything is almost ready. Thanks!

**Comment by brendan-defi** [comment]
@sky-coderay thanks for catching this. i've approved and initiated CI. will merge later today

**Comment by brendan-defi** [comment]
@sky-coderay merged the change in, thank you again for your contribution!

**Pull request merged**
