### PR TITLE
chore: update yarn release and rc file to match package.json spec

### PR DESCRIPTION
**Pull request by JFrankfurt**
**What changed? Why?**
noticed that the yarn release we've got here doesn't match the specified version in package.json, so updating it. 

3.2.4->3.5.0

This appears to fix a bug related to corepack and a missing yarn `URL` import. 

**Notes to reviewers**
see current package.json: https://github.com/base-org/web/blob/master/package.json#L70C1-L71C1

**How has it been tested?**
everything functions as usual locally

### CODE REVIEW

**Review by zencephalon — APPROVED** [review]

**Review by zencephalon — CHANGES_REQUESTED** [review]
Hm, looks like the build fails

**Comment by cb-heimdall** [comment]
Review Error for zencephalon @ 2024-06-13 15:11:02 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by cb-heimdall** [comment]
Review Error for zencephalon @ 2024-06-13 15:11:03 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by JFrankfurt** [comment]
@zencephalon thanks, had to run the new yarn cli to update a few checksums

**Review by zencephalon — APPROVED** [review]

**Pull request merged**
