### PR TITLE
feat: add GRG to ui

### PR DESCRIPTION
**Pull request by gabririgo**
**What changed? Why?**
Added GRG token to ui. GRG is a bridged token included in the [Optimism token list](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/data/GRG/data.json) and actively being bridged from Ethereum L1 to Base L2.

- added GRG logo
- added GRG bridged token details

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by wbnns** [comment]
@gabririgo 

Thanks for taking the time to open this PR. Will leave this open until our team has an opportunity to review.

**Comment by wbnns** [comment]
@gabririgo 

Hi Gabriel, thanks for your patience while this was reviewed. Just wanted to update to let you know that we're only adding assets via the [Superchain Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io) (STL) and are not accepting PRs directly to add to the bridge at this time. This is because not all assets on the STL are on bridge.base.org, as it's a separate review and listing process. 

If you haven't already done so, putting your asset on the STL is the most important step to potentially getting on bridge.base.org in the future, as that's where the team reviews and pulls from. Importantly, it's also where other third party bridges can reference your contract address to potentially add your asset to their bridges in the future as well.

Going ahead and closing this PR but if you have any questions or if there's anything else we can do to help, please don't hesitate to reply here and let us know.

**Comment by gabririgo** [comment]
thank you @wbnns , I can confirm GRG is on [STL](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/data/GRG/data.json) and so its Base address.

**Comment by wbnns** [comment]
@gabririgo 

Ok, great! 👍

**Pull request closed without merging**
