### PR TITLE
Add Vertex to Ecosystem page

### PR DESCRIPTION
**Pull request by tmns**
**What changed? Why?**

`ecosystem.json` was updated to include the relevant data and a logo was added to `public/images/partners`.

**Notes to reviewers**

This information was also previously submitted via the legacy Google Forms process.

Also I originally opened a PR [here](https://github.com/base-org/web/pull/1142) but it was closed due to a perceived lack of ToS, noted in [this comment](https://github.com/base-org/web/pull/1142#issuecomment-2452881164).

However, as I stated in [my reply](https://github.com/base-org/web/pull/1142#issuecomment-2488016703), once the user connects their wallet, they are presented with a ToS modal, which also links out to [our full ToS](https://vertexprotocol.com/docs/TermsOfUse.pdf). Further, the full ToS is also available as a link in the page's navbar.

<details>
<summary>Ex. of ToS modal</summary>

</details>

<details>
<summary>Ex. of ToS link in navbar</summary>

</details>

Does that suffice?

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by wbnns** [comment]
@tmns 

Hello, thanks for the update and work on this. For the requirement, unfortunately, no, it would need to be visible and accessible on the page that is being linked to here in this PR:

2024-12-06 at 08 27 20@2x

**Comment by tmns** [comment]
Hey @wbnns thanks for the update. So just to be clear, being a link within the nav dropdown doesn't work, it needs to be visible without any interaction from the user?

**Comment by wbnns** [comment]
We are adding Vertex in #1387 👍

**Pull request closed without merging**
