### PR TITLE
Bai

### PR DESCRIPTION
**Pull request by christopheSeeka**
**What changed? Why?**
Added our project BlockAI
**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by wbnns** [comment]
@christopheSeeka 

Hi there! Thanks for your PR! Could you please update the landing page to point to the Base subdomain for your platform and confirm what functions are currently available when Base is selected?

**Comment by christopheSeeka** [comment]
You mean change the url to base.blockai.dev in the PR right?

As for available features on Base right now:

- AI Simple Requests via ChatGPT 4o, Gemini 1.5, Orca Mini and Llama 3.1
- Images Generation via Dall-E 3 and Stable Diffusion 3
- Youtube Video AI Summarizer
-  AI Discussion (2 AI Instances discussing a given topic)
-  AI Brainstorming (5 AI instances brainstorming around a given topic and return the result as a MindMap)

All request require a fee in $BAI token, request are stored onchain, picked up by any of the offchain AI agents and the result is stored on IPFS then the is CID sent back on chain to our dapp or to the callback of the calling contract in case of dapp to dapp calls.

Let me know if need anything else.

**Comment by christopheSeeka** [comment]
Updated.

**Review by wbnns — APPROVED** [review]
@christopheSeeka Thanks for the additional insights and for building on Base 🔵

**Comment by wbnns** [comment]
@christopheSeeka Please rebase and resolve the merge conflict.

**Pull request closed without merging**
