### PR TITLE
Fix: Update incorrect documentation link

### PR DESCRIPTION
**Pull request by futreall**
**What changed? Why?**  
Updated an incorrect documentation link to the correct one to ensure accurate navigation for developers.

**Notes to reviewers**  
Replaced the outdated link with the current one from the LayerZero documentation.  

**How has it been tested?**  
Manually verified that the updated link navigates to the intended documentation page.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by futreall** [comment]
@brendan-defi @wbnns Hey ! Sorry to bother you, but could you please review my PR when you have time? There are a few of them because the improvements and fixes were made at different times. I'm leaving for a conference in a day and will be unavailable, so thank you very much in advance for your help !
https://github.com/base-org/web/pull/1384
https://github.com/base-org/web/pull/1383
https://github.com/base-org/op-viem/pull/189

**Comment by futreall** [comment]
@brendan-defi this pls ?

**Review by wbnns — APPROVED** [review]
ACK

@futreall Ty!

**Pull request merged**
