### PR TITLE
Docs Site Revamp: Tutorials

### PR DESCRIPTION
**Pull request by taycaldwell**
**What changed? Why?**
Work in progress: Revamping tutorials

Screenshot 2024-03-18 at 1 57 39 AM

**Notes to reviewers**
This PR is a work in progress.

**How has it been tested?**
Manually

**Does this PR add a new token to the bridge?**

- [x] No, this PR does not add a new token to the bridge
- [ ] I've confirmed this token doesn't use a bridge override
- [ ] I've confirmed this token is an OptimismMintableERC20

Please include evidence of both confirmations above for your reviewers.

### CODE REVIEW

**Comment by taycaldwell** [comment]
TODO:

1. Update front-matter of each tutorial (i.e. Author, last updated, estimated duration, etc.)
2. Convert all tutorials to single page (Currently not listing multi page tutorials)
3. Update styling of single page tutorial pages to reflect updated design

**Comment by jacob-moore-cb** [comment]
This looks good to me so far 👍 just let me know when you're finished and I can take another look if you need me to

**Comment by taycaldwell** [comment]
Updated screenshots:

Screenshot 2024-03-28 at 6 12 07 AM
Screenshot 2024-03-28 at 6 12 40 AM

**Review by jacob-moore-cb — APPROVED** [review]
The tutorial page could use minor adjustments to the layout spacing, but let me know if you want me to tweak that as part of the homepage PR. 

Screenshot 2024-03-28 at 9 50 19 AM

Aside form that this all looks good to me!

**Comment by cb-heimdall** [comment]
Review Error for jacob-moore-cb @ 2024-03-28 17:15:40 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by jacob-moore-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for jacob-moore-cb @ 2024-03-28 17:18:19 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by jacob-moore-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for jacob-moore-cb @ 2024-03-28 17:26:46 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by jacob-moore-cb — APPROVED** [review]

**Review by wbnns — APPROVED** [review]

**Pull request merged**
