### PR TITLE
Docs improvement

### PR DESCRIPTION
**Pull request by cratiu222**
This PR corrects several grammatical errors in the documentation and comments, improving readability and clarity. These changes enhance the overall quality of the project’s written content.

### CODE REVIEW

**Review by briandoyle81CB — CHANGES_REQUESTED** [review]
Thanks for submitting this!  The first three come from legal, so I think the LOE of a full review with them is less than the value of clarity gains.

Good catch with the last typo.  Please remove the first three and I will merge.

**Review by wbnns — APPROVED** [review]
ACK

@cratiu222 Thanks!

**Comment by cb-heimdall** [comment]
Review Error for wbnns @ 2024-10-18 07:07:40 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by brendan-defi** [comment]
Closing this out as these proposed changes are on legal documents.

**Pull request closed without merging**
