### PR TITLE
Listing request Arcadia Games including new format for #1319

### PR DESCRIPTION
**Pull request by L1QU2D**
Removed original PR #1319 to replace with this one with updated formatting included originally.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — APPROVED** [review]
ACK

@L1QU2D Thanks for building on Base 🔵

**Comment by cb-heimdall** [comment]
Review Error for wbnns @ 2024-12-21 00:42:31 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by wbnns** [comment]
@L1QU2D Could you please rebase and sign your commits?

**Comment by L1QU2D** [comment]
@wbnns updated commit signed

**Review by wbnns — APPROVED** [review]
ACK

@L1QU2D Thanks for building on Base 🔵

**Comment by L1QU2D** [comment]
@wbnns i noticed a missing slash in the protocol specifier of the URL, any chance you can adjust and add it or do i need to create a new PR to add the missing forward slash?

**Pull request merged**
