### PR TITLE
Add ECOIN Wallet to Base Ecossystem

### PR DESCRIPTION
**Pull request by ecoin-finance**
**What changed? Why?**
- Initial submission of the ECOIN Wallet app to the Base ecosystem.

**Notes to reviewers**
- The ECOIN Wallet is a cryptocurrency wallet available exclusively for Android devices.
- The app is public and receives regular updates to enhance functionality.
- The latest update includes full support for Base, with features like Deposit, Withdraw, Swap, and Cross-Chain functionality powered by ZetaChain.

**How has it been tested?**
- The app is live and available on Google Play for testing: [ECOIN Wallet on Google Play](https://play.google.com/store/apps/details?id=org.ecoinwallet)  

**To test:**  
1. Create or connect a wallet within the app.  
2. Select **Multichain**, or for the best results, choose **Base** as the network.  
3. Test the following supported features:  
   - Deposit and Withdraw on Base.  
   - Swap functionality built directly into the wallet.  
   - Cross-chain swaps powered by ZetaChain.  
   - Seamless DApp integration.  

### Screenshots  

Below are screenshots of the **ECOIN Wallet** app showcasing its features with Base integration:  

| base (1) | base (2) | base (3) |
|:-------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------:|

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by ecoin-finance** [comment]
Can someone check and approve it?

@wbnns @cb-heimdall

**Comment by wbnns** [comment]
@ecoin-finance 

Hello, thank you for opening this PR and adding support for Base. Unfortunately, we are unable to add ECOIN at this time due to it being primarily focused around the ECOIN token, as described in the fourth bullet under the "Tips for a successful submission" section of the README, and also in the "What to avoid" section in the [Base Editorial Style Guide](https://github.com/base-org/brand-kit/blob/main/guides/editorial-style-guide.md#what-to-avoid).

Once this language is changed and updated, please feel free to open a new pull request and we will re-review. 🙏

**Comment by ecoin-finance** [comment]
Hello, @wbnns @cb-heimdall 

I’d like to clarify a misunderstanding: the ECOIN Wallet is not a token but a product developed by ECOIN Finance, much like how the ECOIN token is a separate product within our ecosystem.

The ECOIN Wallet is a versatile cryptocurrency wallet that supports a wide range of tokens, providing utility far beyond just our native token. By your logic, wallets such as Trust Wallet, which also have associated tokens like TWT, would face similar restrictions, yet they are widely recognized as standalone products serving diverse audiences.

Additionally, my team has spent several weekends working tirelessly to implemen base. We’ve also invested significant effort in making announcements with Base to benefit the broader community.

I kindly ask you to reevaluate the classification of ECOIN Wallet based on its functionality as a crypto wallet rather than conflating it with its association with the ECOIN token.

Thank you for your consideration, and I look forward to your feedback.

**Comment by ecoin-finance** [comment]
@wbnns @cb-heimdall

**Pull request closed without merging**
