### PR TITLE
adding Xocolatl Finance to the ecosystem page 🍫✅

### PR DESCRIPTION
**Pull request by iafhurtado**
**What changed? Why?**
Hi @wbnns, I've updated our scaffold app with a Terms of Service Page and a Privacy Notice page as well, they are located at the Footer of every page.

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by wbnns** [comment]
@iafhurtado 

Thanks for the update! Confirming this is currently in review.

**Comment by iafhurtado** [comment]
Gm @wbnns , just a friendly reminder here. Let me know if there is anything missing for me to fix, have a good start to your week.

**Comment by wbnns** [comment]
@iafhurtado 

Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please reopen a new PR defining the category and subcategory?

We'll do our best to review as soon as possible once you do! 🙏

**Comment by iafhurtado** [comment]
Hi @wbnns ,
I ended up creating a new branch with the changes, I'll go ahead and close this with a comment. 

New PR is here: https://github.com/base-org/web/pull/1428

**Pull request closed without merging**
