### PR TITLE
Update data-indexers.md

### PR DESCRIPTION
**Pull request by sg-tan**
This PR updates documentation. 

**What changed? Why?**

Add Allium as a data indexer for Base data in `data-indexers.md`

**Notes to reviewers**

Contact us if you have any queries.  

**How has it been tested?**
NA. This PR is a documentation change. 

**Does this PR add a new token to the bridge?**

- [x] No, this PR does not add a new token to the bridge
- [NA] I've confirmed this token doesn't use a bridge override
- [NA] I've confirmed this token is an OptimismMintableERC20

Please include evidence of both confirmations above for your reviewers.

### CODE REVIEW

**Comment by wbnns** [comment]
@sg-tan 

Thanks for taking the time to open this PR! We've added this to our backlog, pending to be reviewed.

**Comment by sg-tan** [comment]
Thank you! let me know if you have any questions.

**Review by zencephalon — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for zencephalon @ 2024-03-08 20:26:26 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by zencephalon — CHANGES_REQUESTED** [review]
@sg-tan Could U please rewrite this to not say "us" and "we", etc? It's written from the perspective of Allium but listed on Base.org so it sounds like "we" at Base represent Allium.

**Comment by cb-heimdall** [comment]
Review Error for zencephalon @ 2024-03-08 20:28:11 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by sg-tan** [comment]
> @sg-tan Could U please rewrite this to not say "us" and "we", etc? It's written from the perspective of Allium but listed on Base.org so it sounds like "we" at Base represent Allium.

Hello @zencephalon, thank you for the review. I have updated the descriptions accordingly.

**Review by zencephalon — APPROVED** [review]

**Comment by zencephalon** [comment]
@sg-tan Thank U!

**Pull request merged**
