### PR TITLE
Creating a new category under Tools called "NFT Minting" and updating the existing references of Crossmint

### PR DESCRIPTION
**Pull request by rohit-710**
**What changed? Why?**
- Created a new page called nft-minting.md to add Crossmint's NFT APIs available on Base.
- Updated cross-chain.md to reference support for Base Sepolia on Crossmint.
- Updated sidebar.js to add `tools/nft-minting`.

**Notes to reviewers**
I work as a DevRel Engineer at Crossmint. I had previously created a few PRs that add Crossmint to Base's docs, I have updated the one of the references and created a new NFT minting category.

**How has it been tested?**
Tested locally

### CODE REVIEW

**Comment by rohit-710** [comment]
Hey @zencephalon and @wbnns, can you please review this PR?

**Comment by rohit-710** [comment]
Hey @wbnns @zencephalon, pinging here once again for visibility 🙏

**Comment by wbnns** [comment]
@rohit-710 

Heya! Thanks for this PR! Apologies, we have not had a chance to review this yet.

**Review by zencephalon — APPROVED** [review]

**Comment by rohit-710** [comment]
Hey @wbnns @zencephalon, I see that the PR was approved. Let me know if you can merge it 🙏

**Comment by rohit-710** [comment]
@wbnns @zencephalon 

I just noticed that this page was removed from the docs. I am unable to find it elsewhere. 

Can you please let me know what was the reason for removal? And how can I add it back?

**Pull request merged**
