### PR TITLE
fix: show <0.001 instead of 0 when number gets small

### PR DESCRIPTION
**Pull request by JFrankfurt**
image

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by stevieraykatz — DISMISSED** [review]

**Review by zencephalon — APPROVED** [review]

**Review by zencephalon — COMMENTED** [review]
Hm should we increase the maximum number of fraction digits instead?

**Comment by cb-heimdall** [comment]
Review Error for zencephalon @ 2024-08-22 02:18:03 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by omkarb — APPROVED** [review]

**Review by stevieraykatz — APPROVED** [review]

**Comment by JFrankfurt** [comment]
@zencephalon we could, but that would push the problem into the future and potentially create responsive layout issues on tiny screens

**Review by zencephalon — APPROVED** [review]

**Pull request merged**
