### PR TITLE
Improve Foundry documentation with explicit command parameters

### PR DESCRIPTION
**Pull request by donatik27**
**What changed? Why?**
- Replaced placeholder "..." in Foundry commands with explicit parameters (<CONTRACT_NAME>, <CONTRACT_ADDRESS>)
- Makes documentation more clear and prevents confusion about required command parameters
- Helps developers understand exactly what values they need to provide

**Notes to reviewers**
- No functional changes
- Only documentation clarity improvements
- All URLs, chain IDs and other technical details remain unchanged
- Follows standard documentation practices for command-line examples

**How has it been tested?**
- Verified all links still work
- Confirmed command syntax matches official Foundry documentation
- Checked that all original information is preserved

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by donatik27** [comment]
@cb-heimdall

**Review by ericbrown99 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for ericbrown99 @ 2024-12-02 14:57:08 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by ericbrown99 — APPROVED** [review]

**Comment by donatik27** [comment]
@cb-heimdall Hi! Is there anything I can help with regarding the MFA authentication? Let me know if you need any assistance with the review process.

**Comment by donatik27** [comment]
@ericbrown99 
   Hi! I see that my pull request was approved, but the migration wasn't completed. How can I assist to make it happen, or what should I do on my end?

**Comment by donatik27** [comment]
@brendan-defi  Hi! I see my PR was approved, but the migration hasn't been completed yet. What can I do to help move this forward? Since I noticed you're active in this branch, perhaps you could help us with this issue?

**Review by brendan-defi — APPROVED** [review]

**Comment by brendan-defi** [comment]
Hi @donatik27 thanks for your patience. I've approved and merged.

**Pull request merged**
