### PR TITLE
chore(ecosystem): update cede.store redirection link

### PR DESCRIPTION
**Pull request by 0xnikter**
**What changed? Why?**
Updated cede.store redirection link (added widget prefill parameters + referral)

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Review by zencephalon — APPROVED** [review]

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by zencephalon — APPROVED** [review]

**Review by zencephalon — APPROVED** [review]

**Review by wbnns — CHANGES_REQUESTED** [review]
@0xnikter 

Hi there! Thanks for your patience until we had a chance to review this. I'm nto seeing any difference between the two links when navigating to them. Could you please share more details?

**Comment by 0xnikter** [comment]
> @0xnikter 
> 
> 
> 
> Hi there! Thanks for your patience until we had a chance to review this. I'm nto seeing any difference between the two links when navigating to them. Could you please share more details?

Hey! Thanks for your review. The difference is noticeable only when you have some ETH on the CEX - query params I've added will tell the widget to prefill the send form

**Review by wbnns — APPROVED** [review]
ACK

@0xnikter Thanks for clarifying the change

**Review by omkarb — APPROVED** [review]

**Comment by wbnns** [comment]
@0xnikter 

Hello, apologies, due to a recent issue this will need to be resubmitted as a new PR. If you could please do so and tag me we'll try to bring this in as soon as possible.

**Comment by 0xnikter** [comment]
> @0xnikter 
> 
> 
> 
> Hello, apologies, due to a recent issue this will need to be resubmitted as a new PR. If you could please do so and tag me we'll try to bring this in as soon as possible.

@wbnns what recent issue?

**Pull request closed without merging**
