### PR TITLE
Adding sim Explorer (evm.storage) to Block Explorer docs

### PR DESCRIPTION
**Pull request by dorlevi**
**What changed? Why?**
👋 We added support for Base on evm.storage, adding it here per discussion with your team

**Notes to reviewers**
theres many unique capabilities not available on other similar tools,  we tried to find a good balance between shilling and capturing the unique features
**How has it been tested?**
Minor change, page renders and builds locally 
Screenshot 2024-10-09 at 5 09 41 PM

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@dorlevi 

Thanks for this PR! Could you please update to maintain alphanumerical sorting on the page?

**Comment by wbnns** [comment]
@dorlevi 

Since some time has passed without reply, closing this for now. If you'd like to pursue this change in the future please open a new PR. 🙏

**Comment by dorlevi** [comment]
@wbnns thanks, we were acquired by Dune and thought it is better not to merge considering there might be some project name changes etc... should have updated the ticket.

FWIW, there is no alphanumeric order (or atleast broken with DexGuru/Etherscan) on the page now 
Screenshot 2024-12-18 at 2 22 39 PM

**Pull request closed without merging**
