### PR TITLE
Added PulseLN to Ecosystem

### PR DESCRIPTION
**Pull request by PulseLN**
Added PulseLN info and logo to Base Ecosystem

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@PulseLN 

Hi there! Thanks for building on Base! Could you please update the landing page link to point to a page with Base automatically selected, for folks that would be coming from base.org?

**Comment by wbnns** [comment]
@PulseLN 

Thanks for the updates! We're encountering issues when trying to load PulseLN. For example, each time when loading a new page, the terms of service pop-up appears. Also, when selecting PulseLN, it says the deposit limit has been reached even for the smallest of amounts. Lastly, since most users coming from base.org won't have a Pulse Chain address it will be difficult for them to use this page, for example, to bridge between Binance and Base.

Please resolve the above issues and reopen a new pull request once complete so we can re-review. 🙏

**Comment by PulseLN** [comment]
> @PulseLN
> 
> Thanks for the updates! We're encountering issues when trying to load PulseLN. For example, each time when loading a new page, the terms of service pop-up appears. Also, when selecting PulseLN, it says the deposit limit has been reached even for the smallest of amounts. Lastly, since most users coming from base.org won't have a Pulse Chain address it will be difficult for them to use this page, for example, to bridge between Binance and Base.
> 
> Please resolve the above issues and reopen a new pull request once complete so we can re-review. 🙏

image
The limit error you are seeing is because you are entering a number that is not because the minimum and max limits.

image
1. Pulsechain uses the same address format as Base. 
2. The address to input as the receiver is dependent on the pair you selected, if your output coin is base eth, it will ask for a base address.

**Comment by PulseLN** [comment]
Any update on this?

-------- Original Message --------

**Comment by PulseLN** [comment]
There is an update, please read it and let us know your thoughts.

-------- Original Message --------

**Pull request closed without merging**
