### PR TITLE
add ethgastracker

### PR DESCRIPTION
**Pull request by wslyvh**
**What changed? Why?**

Add ETH Gas Tracker - a tool to monitor and track Ethereum and L2 gas prices, including Base
https://www.ethgastracker.com/network/base

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@wslyvh 

Thanks for this PR! Can you please update the URL to point to Base?

**Comment by wslyvh** [comment]
done @wbnns

**Comment by wbnns** [comment]
@wslyvh 

Looks great, thanks so much! We recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please update defining the category as `infra` and subcategory as `data`?

Should be good to go once you do! 🙏

**Comment by wslyvh** [comment]
done @wbnns

**Review by wbnns — APPROVED** [review]
ACK

@wslyvh Thanks!

**Comment by wbnns** [comment]
@wslyvh Sorry Wesley, looks like one more thing -- can you please rebase and sign your commit?

**Comment by wslyvh** [comment]
done @wbnns

**Review by ericbrown99 — APPROVED** [review]
Looks good, thanks!

**Comment by cb-heimdall** [comment]
Review Error for ericbrown99 @ 2024-12-27 15:06:21 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by wslyvh** [comment]
Sorry, messed up this one @wbnns @ericbrown99 

Signed PR at #1492

**Pull request closed without merging**
