### PR TITLE
Adding Bario Entertainment System to the /ecosystem

### PR DESCRIPTION
**Pull request by panikadak**
**What changed? Why?**
Bario Entertainment System added to the Explore/Apps directory

**Notes to reviewers**

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by wbnns** [comment]
@panikadak 

Thanks for this PR! Super cool. Can you please clarify how this is onchain on Base? I played a game but it seemed to be offchain.

**Comment by panikadak** [comment]
hello @wbnns, bario entertainment system's dApp was recently launched. https://app.baes.so 
i would be appreciated if you'd review again.

**Comment by panikadak** [comment]
@wbnns this PR works, or I need to create new one? (Our onchain app is on)

**Comment by wbnns** [comment]
Closing this since it was a duplicate of a newer PR 🙏

**Comment by panikadak** [comment]
This was the main, and the correct one. This is the one that you can merge
actually.

I just re-did, you can see our dApp also here: app.baes.so

**Comment by panikadak** [comment]
If it is closed, please close all of them. I will recreate that PR.

🥹

**Pull request closed without merging**
