### PR TITLE
Update onboarding.md

### PR DESCRIPTION
**Pull request by lior-crypto**
**What changed? Why?** add tweed to onboarding page

**Notes to reviewers** tweed wallet and checkout 

**How has it been tested?**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>-1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by wbnns — CHANGES_REQUESTED** [review]
@lior-crypto 

Hi there! Could you please update this to point to a Base specific landing page for Base users? This will be helpful so that they can seamlessly leave base.org to continue using Tweed on Base.

**Comment by cb-heimdall** [comment]
Review Error for wbnns @ 2024-11-02 05:33:39 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by wbnns** [comment]
@lior-crypto 

Since it has been some time, going ahead and closing this issue due to inactivity. Please let us know if you'd like to pursue these changes at some point and we can reopen.

**Pull request closed without merging**
